### PR TITLE
Added TMPFS and did some changes for Serial Ports.

### PR DESCRIPTION
**Pull request by andre2308**
Automated the TMPFS installation. #91 
Do some Work to enable access to the Serialports of Synology. Created a startupscript that granted Acess to /dev/ttyACM0 and ttyACM1.  otherwise my ds216 resets the acessrights on reboot. 

To realize these two things, is the Admin Password from the DSM on Installation needed. 

Updated Readme on this two points. 
The needed scripts are in the package.tgz. 

Tested on DS216play with DSM 6.1.7-15284 with openHAB 2.3.003

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-syno-spk/131)

### CODE REVIEW

**Comment by cniweb** [comment]
@andre2308 Can you please implement both adaptations optionally selectable?

**Comment by cniweb** [comment]
I noticed that if an incorrect password was entered, the installation will still be executed. An uninstall is then not possible.

**Comment by andre2308** [comment]
I will look for this. But it makes some time :( 
If you have any suggestions, thats will be nice

**Comment by andre2308** [comment]
Hey cniweb,

i made some changes, now it runs without a Password. On my first version this was not. Don´t ask me why... It confuse me too.

It woud nice if you can verify this. 

I tested for myself on my DS216play and on a virtual DSM. Both works without a Password. Even after change the Admin Password. 

https://github.com/andre2308/openhab-syno-spk/tree/andre2308-TMPFS

If this is good i will work on the selectable the two Options. When i'am done, i will take a new PR

Greetings André

**Comment by cniweb** [comment]
@andre2308  Looks better. You do not need sudo, the package will be installed as root user.

**Comment by andre2308** [comment]
Okay Thank you.

As writed, first time says it without sudo, permission denied.. wired thing. 

Now i work on choiceable

**Pull request merged**
