### PR TITLE
Change user group and access rights

### LINKED ISSUE #123: Logging not working with fresh untouched installation
The logging ist not working after success installation in /SmartHome/openHAB/. The file /SmartHome/openHAB/userdata/logs/openhab.log has a size of 0 bytes.

**Systeminformation:**
- DS214play
- DSM 6.1.4-15217 Update 5
- Java: 8.0 151-0014

**Reproduction:**
1. Install synology package openHAB-2.2.0.010-syno-noarch-0.001.spk to /volume1/SmartHome/openHAB/ and http port 9090
2. configure UI via http://YourDsIp:9090
3. navigate with File Station to /volume1/SmartHome/openHAB/userdata/logs/openhab.log --> size is 0 bytes

In my opinion a log entry should be written after module paper ui is started

The content of the file '/SmartHome/openHAB/userdata/etc/org.ops4j.pax.logging.cfg':
```{r, engine='bash', count_lines}
# Common pattern layout for appenders
#log4j2.pattern = %d{ISO8601} | %-5p | %-16t | %-32c{1} | %X{bundle.id} - %X{bundle.name} - %X{bundle.version} | %m%n

# Root logger
log4j2.rootLogger.level = WARN
log4j2.rootLogger.appenderRefs = out, osgi
log4j2.rootLogger.appenderRef.out.ref = LOGFILE
log4j2.rootLogger.appenderRef.osgi.ref = OSGI

# Karaf Shell logger
log4j2.logger.shell.name = org.apache.karaf.shell.support
log4j2.logger.shell.level = OFF
log4j2.logger.shell.appenderRefs = stdout
log4j2.logger.shell.appenderRef.stdout.ref = STDOUT

# Security audit logger
log4j2.logger.audit.name = org.apache.karaf.jaas.modules.audit
log4j2.logger.audit.level = INFO
log4j2.logger.audit.additivity = false
log4j2.logger.audit.appenderRefs = audit
log4j2.logger.audit.appenderRef.audit.ref = AUDIT

# openHAB specific logger configuration

log4j2.logger.openhab.name = org.openhab
log4j2.logger.openhab.level = INFO

log4j2.logger.smarthome.name = org.eclipse.smarthome
log4j2.logger.smarthome.level = INFO

log4j2.logger.smarthomeItemStateEvent.name = smarthome.event.ItemStateEvent
log4j2.logger.smarthomeItemStateEvent.level = ERROR
log4j2.logger.smarthomeItemAddedEvent.name = smarthome.event.ItemAddedEvent
log4j2.logger.smarthomeItemAddedEvent.level = ERROR
log4j2.logger.smarthomeItemRemovedEvent.name = smarthome.event.ItemRemovedEvent
log4j2.logger.smarthomeItemRemovedEvent.level = ERROR
log4j2.logger.smarthomeThingStatusInfoEvent.name = smarthome.event.ThingStatusInfoEvent
log4j2.logger.smarthomeThingStatusInfoEvent.level = ERROR
log4j2.logger.smarthomeThingAddedEvent.name = smarthome.event.ThingAddedEvent
log4j2.logger.smarthomeThingAddedEvent.level = ERROR
log4j2.logger.smarthomeThingRemovedEvent.name = smarthome.event.ThingRemovedEvent
log4j2.logger.smarthomeThingRemovedEvent.level = ERROR
log4j2.logger.smarthomeInboxUpdatedEvent.name = smarthome.event.InboxUpdatedEvent
log4j2.logger.smarthomeInboxUpdatedEvent.level = ERROR

log4j2.logger.events.name = smarthome.event
log4j2.logger.events.level = INFO
log4j2.logger.events.additivity = false
log4j2.logger.events.appenderRefs = event
log4j2.logger.events.appenderRef.event.ref = EVENT
log4j2.logger.events.appenderRef.osgi.ref = OSGI

log4j2.logger.jupnp.name = org.jupnp
log4j2.logger.jupnp.level = ERROR

log4j2.logger.jmdns.name = javax.jmdns
log4j2.logger.jmdns.level = ERROR

# This suppresses all Maven download issues from the log when doing feature installations
# as we are logging errors ourselves in a nicer way anyhow.
log4j2.logger.paxurl.name = org.ops4j.pax.url.mvn.internal.AetherBasedResolver
log4j2.logger.paxurl.level = ERROR

# Filters known issues of pax-web (issue link to be added here).
# Can be removed once the issues are resolved in an upcoming version.
log4j2.logger.paxweb.name = org.ops4j.pax.web.pax-web-runtime
log4j2.logger.paxweb.level = OFF

# Filters known issues of lsp4j, see
# https://github.com/eclipse/smarthome/issues/4639
# https://github.com/eclipse/smarthome/issues/4629
# https://github.com/eclipse/smarthome/issues/4643
# Can be removed once the issues are resolved in an upcoming version.
log4j2.logger.lsp4j.name = org.eclipse.lsp4j
log4j2.logger.lsp4j.level = OFF

# Filters known issues of KarServiceImpl, see
# https://github.com/openhab/openhab-distro/issues/519#issuecomment-351944506
# Can be removed once the issues are resolved in an upcoming version.
log4j2.logger.karservice.name = org.apache.karaf.kar.internal.KarServiceImpl
log4j2.logger.karservice.level = ERROR


# Appenders configuration

# Console appender not used by default (see log4j2.rootLogger.appenderRefs)
log4j2.appender.console.type = Console
log4j2.appender.console.name = STDOUT
log4j2.appender.console.layout.type = PatternLayout
log4j2.appender.console.layout.pattern = %d{HH:mm:ss.SSS} [%-5.5p] [%-36.36c] - %m%n

# Rolling file appender
log4j2.appender.out.type = RollingRandomAccessFile
log4j2.appender.out.name = LOGFILE
log4j2.appender.out.fileName = ${openhab.logdir}/openhab.log
log4j2.appender.out.filePattern = ${openhab.logdir}/openhab.log.%i
log4j2.appender.out.immediateFlush = true
log4j2.appender.out.append = true
log4j2.appender.out.layout.type = PatternLayout
log4j2.appender.out.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%-36.36c] - %m%n
log4j2.appender.out.policies.type = Policies
log4j2.appender.out.policies.size.type = SizeBasedTriggeringPolicy
log4j2.appender.out.policies.size.size = 16MB

# Event log appender
log4j2.appender.event.type = RollingRandomAccessFile
log4j2.appender.event.name = EVENT
log4j2.appender.event.fileName = ${openhab.logdir}/events.log
log4j2.appender.event.filePattern = ${openhab.logdir}/events.log.%i
log4j2.appender.event.immediateFlush = true
log4j2.appender.event.append = true
log4j2.appender.event.layout.type = PatternLayout
log4j2.appender.event.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%-26.26c] - %m%n
log4j2.appender.event.policies.type = Policies
log4j2.appender.event.policies.size.type = SizeBasedTriggeringPolicy
log4j2.appender.event.policies.size.size = 16MB

# Audit file appender
log4j2.appender.audit.type = RollingRandomAccessFile
log4j2.appender.audit.name = AUDIT
log4j2.appender.audit.fileName = ${openhab.logdir}/audit.log
log4j2.appender.audit.filePattern = ${openhab.logdir}/audit.log.%i
log4j2.appender.audit.append = true
log4j2.appender.audit.layout.type = PatternLayout
log4j2.appender.audit.layout.pattern = %d{yyyy-MM-dd HH:mm:ss.SSS} [%-5.5p] [%-36.36c] - %m%n
log4j2.appender.audit.policies.type = Policies
log4j2.appender.audit.policies.size.type = SizeBasedTriggeringPolicy
log4j2.appender.audit.policies.size.size = 8MB

# OSGi appender
log4j2.appender.osgi.type = PaxOsgi
log4j2.appender.osgi.name = OSGI
log4j2.appender.osgi.filter = *
```

### PR DESCRIPTION
**Pull request by cniweb**
Fixes #123

Signed-off-by: Christian Häussler <c-n-i@web.de> (github: @cniweb)

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-syno-spk/126)

### CODE REVIEW

**Comment by dfrap** [comment]
My testing of these changes does not fix  #123  My system still does not log, but perhaps it fixes the issue for others.  

N.B. Using chmod removes the ACL permissions that were set with:
`...synoacltool -add ${filename} ${DAEMON_ACL}` 
`DAEMON_ACL="user:${DAEMON_USER}:allow:rwxpdDaARWc--:fd--"`
If the ACL permissions are not useful, perhaps setting them should be removed from the install script.  But I would suggest the synoacltool commands remain to be used in some future revision. 

When an ACL is set for a directory, the ls command will indicate and ACL is set by showing a + following the permissions. 
ls -e with -l will show syno-acl permission details for any directory.  root permission or sudo is needed to see the same details with synoacltool -get  I am still puzzled as to why the ACL and Unix access permissions are different between userdata, conf, and addons.  I regret that I have not been able to spend the time to debug the cause.  

---

Review status: 0 of 1 files reviewed at latest revision, all discussions resolved.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/openhab/openhab-syno-spk/126#-:-L34kXRdzm7RbFdaIwPm:bsoiizk)*

**Comment by IRTermite** [comment]
Concur with @dfrap 
I too am still getting 0 sized Log file and nothing added to config on a fresh SNAPSHOT install.
Manually set the perms too 770 on the paths as well for conf and userdata. Didn't touch addons yet. Still nothing. 
This is installing to /var/services/homes/openhab
2.3.0.001-SNAPSHOT
DSM 5.2-5644

**Comment by dfrap** [comment]
@IRTermite I finally got logging working by updating the logging config file.   The root cause appears to be the change in Karaf versions at build #1009. See Karaf Upgrade4 for details: https://community.openhab.org/t/karaf-upgrade/33208

It appears that the logging config file is not upgraded on install of new versions so the user needs to upgrade it manually.  So my ‘fix’ was to remove /volume1/public/openHAB/userdata/etc/org.ops4j.pax.logging.cfg and replace it with the version from https://openhab.ci.cloudbees.com/job/openHAB-Distribution/lastSuccessfulBuild/artifact/distributions/openhab/target/openhab-2.3.0-SNAPSHOT.zip1

So if your Synology openHAB won’t log, the process seems to be:
Uninstall the openHAB package
Update the Karaf customization file: org.ops4j.pax.logging.cfg
Reinstall your desired level of openHAB - 2.2.0.010 works for me

**Comment by cniweb** [comment]
@kaikreuzer Is it necessary to delete org.ops4j.pax.logging.cfg during an update?

**Comment by kaikreuzer** [comment]
@cniweb It should be overwritten by the latest version, yes.
This means that user customisations of the logging will be lost until we have a solution for https://github.com/openhab/openhab-distro/issues/516.

**Pull request merged**
