### PR TITLE
Removed currently not working information

### PR DESCRIPTION
**Pull request by hphde**
Signed-off-by: Heinz Peter Hippenstiel <github.hph@xoxy.net>

---
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-syno-spk/58)

### CODE REVIEW

**Comment by cniweb** [comment]
I think this is not necessary. If it works properly, the description will fit.

**Comment by hphde** [comment]
Where is the part that does the check against `/volume1/public/openHAB2/conf`?

**Comment by cniweb** [comment]
https://github.com/openhab/openhab-syno-spk/blob/master/scripts/installer.sh#L98

**Comment by hphde** [comment]
Ooops. Now I remember ... need to test if that works.
And the addons stuff below? I saw that discussion

**Pull request closed without merging**
