### PR TITLE
Changes user info to create userdata folder before

### PR DESCRIPTION
**Pull request by rkrausen**
This change is [Reviewable](https://reviewable.io/reviews/openhab/openhab-syno-spk/114)

### CODE REVIEW

**Comment by cniweb** [comment]
Why did you close your 4 PR?

**Comment by cniweb** [comment]
@rkrausen Why did you close your 4 PR?

**Comment by rkrausen** [comment]
There was a problem. The system shows me a Cross in one of 3 tests and i can't change/repair.

**Comment by cniweb** [comment]
Sorry, that´s normal. The continuous-integration/feram check work´s not fine.
Can you make a new PR with all the 4 changes?

**Comment by rkrausen** [comment]
Can you explain how to combine these in 1 PR

________________________________
Von: Christian Häussler <notifications@github.com>
Gesendet: Donnerstag, 16. November 2017 18:03:43
An: openhab/openhab-syno-spk
Cc: Rene Krausen; Mention
Betreff: Re: [openhab/openhab-syno-spk] Changes user info to create userdata folder before (#114)


Sorry, that´s normal. The continuous-integration/feram check work´s not fine.
Can you make a new PR with all the 4 changes?

**Comment by cniweb** [comment]
You create a fork from this repository, then create a branch in your repository and make the 4 changes (commits). Then you make a pull request to my master.

**Comment by cniweb** [comment]
See: https://help.github.com/articles/github-flow/

**Pull request closed without merging**
